DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS todos;
CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  surname VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE todos (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  todo VARCHAR(250) NOT NULL,
  user_id VARCHAR(250) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id))
);